// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace fourth.people {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Employee {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_fourth_people_Employee__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::fourth.people.Employee, global::fourth.people.Employee.Builder> internal__static_fourth_people_Employee__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static Employee() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            "ChRwcm90by9lbXBsb3llZS5wcm90bxINZm91cnRoLnBlb3BsZSI4CghFbXBs" + 
            "b3llZRIMCgRuYW1lGAEgAigJEgsKA2FnZRgCIAIoBRIRCgluaV9udW1iZXIY" + 
            "AyACKAk=");
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_fourth_people_Employee__Descriptor = Descriptor.MessageTypes[0];
          internal__static_fourth_people_Employee__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::fourth.people.Employee, global::fourth.people.Employee.Builder>(internal__static_fourth_people_Employee__Descriptor,
                  new string[] { "Name", "Age", "NiNumber", });
          return null;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Employee : pb::GeneratedMessage<Employee, Employee.Builder> {
    private Employee() { }
    private static readonly Employee defaultInstance = new Employee().MakeReadOnly();
    private static readonly string[] _employeeFieldNames = new string[] { "age", "name", "ni_number" };
    private static readonly uint[] _employeeFieldTags = new uint[] { 16, 10, 26 };
    public static Employee DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override Employee DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override Employee ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::fourth.people.Proto.Employee.internal__static_fourth_people_Employee__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<Employee, Employee.Builder> InternalFieldAccessors {
      get { return global::fourth.people.Proto.Employee.internal__static_fourth_people_Employee__FieldAccessorTable; }
    }
    
    public const int NameFieldNumber = 1;
    private bool hasName;
    private string name_ = "";
    public bool HasName {
      get { return hasName; }
    }
    public string Name {
      get { return name_; }
    }
    
    public const int AgeFieldNumber = 2;
    private bool hasAge;
    private int age_;
    public bool HasAge {
      get { return hasAge; }
    }
    public int Age {
      get { return age_; }
    }
    
    public const int NiNumberFieldNumber = 3;
    private bool hasNiNumber;
    private string niNumber_ = "";
    public bool HasNiNumber {
      get { return hasNiNumber; }
    }
    public string NiNumber {
      get { return niNumber_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasName) return false;
        if (!hasAge) return false;
        if (!hasNiNumber) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _employeeFieldNames;
      if (hasName) {
        output.WriteString(1, field_names[1], Name);
      }
      if (hasAge) {
        output.WriteInt32(2, field_names[0], Age);
      }
      if (hasNiNumber) {
        output.WriteString(3, field_names[2], NiNumber);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasName) {
          size += pb::CodedOutputStream.ComputeStringSize(1, Name);
        }
        if (hasAge) {
          size += pb::CodedOutputStream.ComputeInt32Size(2, Age);
        }
        if (hasNiNumber) {
          size += pb::CodedOutputStream.ComputeStringSize(3, NiNumber);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static Employee ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Employee ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Employee ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Employee ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Employee ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Employee ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Employee ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static Employee ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static Employee ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Employee ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private Employee MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(Employee prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<Employee, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(Employee cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private Employee result;
      
      private Employee PrepareBuilder() {
        if (resultIsReadOnly) {
          Employee original = result;
          result = new Employee();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override Employee MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::fourth.people.Employee.Descriptor; }
      }
      
      public override Employee DefaultInstanceForType {
        get { return global::fourth.people.Employee.DefaultInstance; }
      }
      
      public override Employee BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is Employee) {
          return MergeFrom((Employee) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(Employee other) {
        if (other == global::fourth.people.Employee.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasName) {
          Name = other.Name;
        }
        if (other.HasAge) {
          Age = other.Age;
        }
        if (other.HasNiNumber) {
          NiNumber = other.NiNumber;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_employeeFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _employeeFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasName = input.ReadString(ref result.name_);
              break;
            }
            case 16: {
              result.hasAge = input.ReadInt32(ref result.age_);
              break;
            }
            case 26: {
              result.hasNiNumber = input.ReadString(ref result.niNumber_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasName {
        get { return result.hasName; }
      }
      public string Name {
        get { return result.Name; }
        set { SetName(value); }
      }
      public Builder SetName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder ClearName() {
        PrepareBuilder();
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      public bool HasAge {
        get { return result.hasAge; }
      }
      public int Age {
        get { return result.Age; }
        set { SetAge(value); }
      }
      public Builder SetAge(int value) {
        PrepareBuilder();
        result.hasAge = true;
        result.age_ = value;
        return this;
      }
      public Builder ClearAge() {
        PrepareBuilder();
        result.hasAge = false;
        result.age_ = 0;
        return this;
      }
      
      public bool HasNiNumber {
        get { return result.hasNiNumber; }
      }
      public string NiNumber {
        get { return result.NiNumber; }
        set { SetNiNumber(value); }
      }
      public Builder SetNiNumber(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasNiNumber = true;
        result.niNumber_ = value;
        return this;
      }
      public Builder ClearNiNumber() {
        PrepareBuilder();
        result.hasNiNumber = false;
        result.niNumber_ = "";
        return this;
      }
    }
    static Employee() {
      object.ReferenceEquals(global::fourth.people.Proto.Employee.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
